config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "todos#index"

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    validates :title, presence: true
    validates :body, presence:true, length:{minimum:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = List.all
  end

  def show 
    @todo = List.find(params[:id])
  end

  def new 
    @todo = List.new
  end

  def create
    @todo = List.new(article_params)

    if @todo.save
      redirect_to todo_path(@todo)
    else
      render :new
    end
  end

  def edit
    @todo = List.find(params[:id])
  end

  def update
    @todo = List.find(params[:id])

    if @todo.update(article_params)
      redirect_to todo_path(@todo)
    else
      render :edit
    end
  end

  def destroy
    @todo = List.find(params[:id])
    @todo.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:list).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: todo, url:path do |form| %>
    <div>
      <label class="form__label" for="todo">~ Today I need to ~</label>

      <%= form.text_field :title , :class => "form__input" ,placeholder: "title" %>
      <% todo.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
      <% end %>

      <%= form.text_field :body , :class => "form__input" ,placeholder: "description" %>
      <% todo.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
      <% end %>

      <br>
      <button type="submit" name="commit" class="button"><span>Submit</span></button>
    </div>
  <% end %>

app/views/todos/edit.html.erb
<section class="container">
  <div class="heading">
    <img class="heading__img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/756881/laptop.svg">
    <h1 class="heading__title">To-Do List</h1>
  </div>

  <%= render "form", todo: @todo , path: todo_path %>
</section>

app/views/todos/index.html.erb
<section class="container">
  <div class="heading">
    <img class="heading__img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/756881/laptop.svg">
    <h1 class="heading__title">To-Do List</h1>
  </div>
  <%=link_to "<button class=button><span>New</span></button>".html_safe, new_todo_path  %>
  <div>
    <ul class="toDoList">
      <% @todos.each do |element|%>
        <li> 
          <div class="element">
             <a href="<%= todo_path(element) %>">
                <%= element.title %>
             </a>
             <%= element.created_at%> 
          </div>
        </li>
      <%end%>
    </ul>
  </div>
</section>

app/views/todos/new.html.erb
<section class="container">
  <div class="heading">
    <img class="heading__img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/756881/laptop.svg">
    <h1 class="heading__title">To-Do List</h1>
  </div>

  <%= render "form", todo: @todo , path: todos_path %>
</section>

app/views/todos/show.html.erb
<section class="container">
  <div class="heading">
    <img class="heading__img" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/756881/laptop.svg">
    <h1 class="heading__title"><%= @todo.title %></h1>
  </div>
  
  <div>
    <p class="form__label"><%= @todo.body%> </p>
  </div>
    <%=link_to "<button class=button><span>Return</span></button>".html_safe, root_path %>
    <div class="element">
      <%=link_to "<button class=button><span>Edit</span></button>".html_safe, edit_todo_path(@todo)  %>
      <%= link_to "<button class=button><span>Delete</span></button>".html_safe, todo_path(@todo),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    <div>
</section>